Change 'set-hand-width' to 'hand-width'
pazeshun/rtmros_tutorials pull request #2
Opened 2018-12-03 09:37 UTC by Affonso-Gui

Open to discussions

2018-12-04 06:06 UTC, pazeshun requested changes

2018-12-04 06:06 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +    (assert (= (length vec) 4))
Can you add printing error message here?

2018-12-05 02:14 UTC, Affonso-Gui commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +    (assert (= (length vec) 4))
Added

2019-04-02 11:01 UTC, pazeshun requested changes

2019-04-02 11:01 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +       (effort
`(listp effort)` or `(vectorp effort)`?

2019-04-02 11:01 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +       (effort
You need to check length of `effort`.

2019-04-03 09:27 UTC, Affonso-Gui commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +       (effort
Fixed it and added more typecheck to surrounding functions

2019-04-03 12:09 UTC, pazeshun requested changes

2019-04-03 12:09 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +            (assert (= (length av) (* 2 +hironx-hand-servo-num+))))
Add printing info like https://github.com/pazeshun/rtmros_tutorials/pull/2/files#diff-6cffc2ae28c25e5e9c2a0377adcf4031R367

2019-04-03 12:09 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +            (assert (= (length av) +hironx-hand-servo-num+)))))
Add printing info like https://github.com/pazeshun/rtmros_tutorials/pull/2/files#diff-6cffc2ae28c25e5e9c2a0377adcf4031R367

2019-04-03 12:09 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +               (assert (= (length effort) (* 2 +hironx-hand-servo-num+))))
Add printing info like https://github.com/pazeshun/rtmros_tutorials/pull/2/files#diff-6cffc2ae28c25e5e9c2a0377adcf4031R367

2019-04-03 12:09 UTC, pazeshun commented on hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l
> +               (assert (= (length effort) +hironx-hand-servo-num+))))
Add printing info like https://github.com/pazeshun/rtmros_tutorials/pull/2/files#diff-6cffc2ae28c25e5e9c2a0377adcf4031R367

2019-04-04 15:04 UTC, pazeshun approved these changes

2019-04-04 15:04 UTC, pazeshun commented
I will merge this after checking in next demos.

2019-04-05 08:43 UTC, Affonso-Gui commented
@pazeshun Forget to mention, but this will have better debugging printing information with https://github.com/euslisp/EusLisp/pull/363
https://github.com/pazeshun/rtmros_tutorials/blob/4ddedec446628ce74dc146641e01028d1f5f0aad/hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l#L259-L260

2019-04-08 08:54 UTC, merged